package parser;
/* Generated By:JavaCC: Do not edit this line. XYZParserConstants.java */
public interface XYZParserConstants {

  int EOF = 0;
  int NOT = 6;
  int ASSIGN = 7;
  int AND = 8;
  int LT = 9;
  int PLUS = 10;
  int MINUS = 11;
  int MUL = 12;
  int OPER = 13;
  int PUBLIC = 14;
  int CLASS = 15;
  int EXTENDS = 16;
  int STATIC = 17;
  int VOID = 18;
  int MAIN = 19;
  int STRING = 20;
  int IF = 21;
  int ELSE = 22;
  int DO = 23;
  int WHILE = 24;
  int NEW = 25;
  int LENGTH = 26;
  int PRINT = 27;
  int INT = 28;
  int BOOLEAN = 29;
  int TRUE = 30;
  int FALSE = 31;
  int THIS = 32;
  int RETURN = 33;
  int DOUBLE = 34;
  int KEYWORD = 35;
  int LBRACE = 36;
  int RBRACE = 37;
  int LBRACK = 38;
  int RBRACK = 39;
  int LPAREN = 40;
  int RPAREN = 41;
  int COMMA = 42;
  int SEMI = 43;
  int DOT = 44;
  int SIGN = 45;
  int INTLITERAL = 46;
  int REALLITERAL = 47;
  int ID = 48;
  int ONE_LINE_COMMENT = 49;
  int LINES_COMMENT = 50;
  int FORMAL_COMMENT = 51;
  int COMMENT = 52;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"!\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<OPER>",
    "\"public\"",
    "\"class\"",
    "\"extends\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"new\"",
    "\"length\"",
    "\"System.out.println\"",
    "\"int\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"return\"",
    "\"double\"",
    "<KEYWORD>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "<SIGN>",
    "<INTLITERAL>",
    "<REALLITERAL>",
    "<ID>",
    "<ONE_LINE_COMMENT>",
    "<LINES_COMMENT>",
    "<FORMAL_COMMENT>",
    "<COMMENT>",
  };

}
