package ast;
/* Generated By:JJTree: Do not edit this line. JudgeExpNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JudgeExpNode extends SimpleNode {
  public JudgeExpNode(int id) {
    super(id);
  }

  public JudgeExpNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dd4026299fddf7ea87e2b0c93cef1db7 (do not edit this line) */
