package ast;
/* Generated By:JJTree: Do not edit this line. MainClass.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class MainClass extends SimpleNode {
  public MainClass(int id) {
    super(id);
  }

  public MainClass(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=100f11bac68ed5b6a3f52e9b35ab83b7 (do not edit this line) */
