package ast;
/* Generated By:JJTree: Do not edit this line. MethodNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class MethodNode extends SimpleNode {
  public MethodNode(int id) {
    super(id);
  }

  public MethodNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a614ed4abe22f798dfbb3e3b0a398773 (do not edit this line) */
