package ast;
/* Generated By:JJTree: Do not edit this line. NewExpNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class NewExpNode extends SimpleNode {
  public NewExpNode(int id) {
    super(id);
  }

  public NewExpNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ad0c0bf5a48e8b2e51bd13d2e8e85f22 (do not edit this line) */
