package ast;
/* Generated By:JJTree: Do not edit this line. PrimitiveTypeNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class PrimitiveTypeNode extends SimpleNode {
  public PrimitiveTypeNode(int id) {
    super(id);
  }

  public PrimitiveTypeNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=34460d319774477f2638d1135e183a6d (do not edit this line) */
