package ast;
/* Generated By:JavaCC: Do not edit this line. XYZParserTreeConstants.java Version 4.2 */
public interface XYZParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTPROGRAM = 2;
  public int JJTMAINCLASS = 3;
  public int JJTCLASSDECL = 4;
  public int JJTEXTENDNODE = 5;
  public int JJTIFSTATEMENTNODE = 6;
  public int JJTWHILESTATEMENTNODE = 7;
  public int JJTJUDGEEXPNODE = 8;
  public int JJTSINGLESTATEMENTNODE = 9;
  public int JJTPRINTSTATEMENTNODE = 10;
  public int JJTASSIGNSTATEMENTNODE = 11;
  public int JJTASSIGNLEFTNODE = 12;
  public int JJTASSIGNRIGHTNODE = 13;
  public int JJTVARDECLNODE = 14;
  public int JJTMETHODNODE = 15;
  public int JJTFORMALLISTNODE = 16;
  public int JJTFORMALRESTNODE = 17;
  public int JJTRETURNSTATEMENTNODE = 18;
  public int JJTPRIMITIVETYPENODE = 19;
  public int JJTOBJECTTYPENODE = 20;
  public int JJTEXPNODE = 21;
  public int JJTNEWEXPNODE = 22;
  public int JJTINTARRAYNODE = 23;
  public int JJTDOUBLEARRAYNODE = 24;
  public int JJTANDEXPNODE = 25;
  public int JJTNOTEXPNODE = 26;
  public int JJTLESSEXPNODE = 27;
  public int JJTADDEXPNODE = 28;
  public int JJTMINUSEXPNODE = 29;
  public int JJTMULTIEXPNODE = 30;
  public int JJTSIGNEXPNODE = 31;
  public int JJTLITERALCONSTANTNODE = 32;
  public int JJTIDEXPNODE = 33;
  public int JJTINDEXNODE = 34;
  public int JJTDOTLENGTHNODE = 35;
  public int JJTINVOKEFUNCTIONNODE = 36;
  public int JJTIDNODE = 37;
  public int JJTTHISNODE = 38;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Program",
    "MainClass",
    "ClassDecl",
    "ExtendNode",
    "IfStatementNode",
    "WhileStatementNode",
    "JudgeExpNode",
    "SingleStatementNode",
    "PrintStatementNode",
    "AssignStatementNode",
    "AssignLeftNode",
    "AssignRightNode",
    "VarDeclNode",
    "MethodNode",
    "FormalListNode",
    "FormalRestNode",
    "ReturnStatementNode",
    "PrimitiveTypeNode",
    "ObjectTypeNode",
    "ExpNode",
    "NewExpNode",
    "IntArrayNode",
    "DoubleArrayNode",
    "AndExpNode",
    "NotExpNode",
    "LessExpNode",
    "AddExpNode",
    "MinusExpNode",
    "MultiExpNode",
    "SignExpNode",
    "LiteralConstantNode",
    "IDExpNode",
    "IndexNode",
    "DotLengthNode",
    "InvokeFunctionNode",
    "IDNode",
    "ThisNode",
  };
}
/* JavaCC - OriginalChecksum=6432240027bfd9fe0ea86d7829f15fe5 (do not edit this line) */
