/* Generated By:JavaCC: Do not edit this line. XYZParserVisitor.java Version 4.2 */
public interface XYZParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Root node, Object data);
  public Object visit(Program node, Object data);
  public Object visit(MainClass node, Object data);
  public Object visit(ClassDecl node, Object data);
  public Object visit(IfStatementNode node, Object data);
  public Object visit(WhileStatementNode node, Object data);
  public Object visit(SingleStatementNode node, Object data);
  public Object visit(VarDeclNode node, Object data);
  public Object visit(MethodNode node, Object data);
  public Object visit(FormalListNode node, Object data);
  public Object visit(FormalRestNode node, Object data);
  public Object visit(ReturnStatementNode node, Object data);
}
/* JavaCC - OriginalChecksum=43d844ba1baa942cca2ed8c44ebe1e73 (do not edit this line) */
