package parser2;

/* Generated By:JJTree: Do not edit this line. ReturnStatementNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ReturnStatementNode extends SimpleNode {
  public ReturnStatementNode(int id) {
    super(id);
  }

  public ReturnStatementNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=86dc1584778e49f53db26447f07af3ec (do not edit this line) */
