package parser2;

/* Generated By:JJTree: Do not edit this line. SingleStatementNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SingleStatementNode extends SimpleNode {
  public SingleStatementNode(int id) {
    super(id);
  }

  public SingleStatementNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9b4f9b83d37f2344df55df7d52345bd5 (do not edit this line) */
