package parser2;

/* Generated By:JavaCC: Do not edit this line. XYZParserTreeConstants.java Version 4.2 */
public interface XYZParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTPROGRAM = 2;
  public int JJTMAINCLASS = 3;
  public int JJTCLASSDECL = 4;
  public int JJTIFSTATEMENTNODE = 5;
  public int JJTWHILESTATEMENTNODE = 6;
  public int JJTSINGLESTATEMENTNODE = 7;
  public int JJTVARDECLNODE = 8;
  public int JJTMETHODNODE = 9;
  public int JJTFORMALLISTNODE = 10;
  public int JJTFORMALRESTNODE = 11;
  public int JJTRETURNSTATEMENTNODE = 12;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Program",
    "MainClass",
    "ClassDecl",
    "IfStatementNode",
    "WhileStatementNode",
    "SingleStatementNode",
    "VarDeclNode",
    "MethodNode",
    "FormalListNode",
    "FormalRestNode",
    "ReturnStatementNode",
  };
}
/* JavaCC - OriginalChecksum=73540e7ca251e02cca35a4cf3fc783b8 (do not edit this line) */
