package ast;
/* Generated By:JJTree: Do not edit this line. DoubleArrayNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class DoubleArrayNode extends SimpleNode {
  public DoubleArrayNode(int id) {
    super(id);
  }

  public DoubleArrayNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=70758f2aac6ba0cdcbf5119cda086471 (do not edit this line) */
