package ast;
/* Generated By:JJTree: Do not edit this line. IntArrayNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class IntArrayNode extends SimpleNode {
  public IntArrayNode(int id) {
    super(id);
  }

  public IntArrayNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4aaf9628298cc91168c4a0ee21c1bd35 (do not edit this line) */
