package ast;
/* Generated By:JJTree: Do not edit this line. InvokeFunctionNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class InvokeFunctionNode extends SimpleNode {
  public InvokeFunctionNode(int id) {
    super(id);
  }

  public InvokeFunctionNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3504a6addf395eb60e8ae91f637aa9f7 (do not edit this line) */
