package ast;
/* Generated By:JJTree: Do not edit this line. ObjectInstanceNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ObjectInstanceNode extends SimpleNode {
  public ObjectInstanceNode(int id) {
    super(id);
  }

  public ObjectInstanceNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7a8cb5baa043f51923a94c253d268836 (do not edit this line) */
