package ast;
/* Generated By:JJTree: Do not edit this line. WhileStatementNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class WhileStatementNode extends SimpleNode {
  public WhileStatementNode(int id) {
    super(id);
  }

  public WhileStatementNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=05b1105cc70dcc3c71f906664a26bdd9 (do not edit this line) */
