/* Generated By:JJTree: Do not edit this line. AssignLeftNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class AssignLeftNode extends SimpleNode {
  public AssignLeftNode(int id) {
    super(id);
  }

  public AssignLeftNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=90eb56205d6ef666994c0bc6e211f3a0 (do not edit this line) */
