/* Generated By:JJTree: Do not edit this line. ConstantElementNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ConstantElementNode extends SimpleNode {
  public ConstantElementNode(int id) {
    super(id);
  }

  public ConstantElementNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4c9aaa54ccf43de94e6a6efb97783c62 (do not edit this line) */
