/* Generated By:JJTree: Do not edit this line. ObjectTypeNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ObjectTypeNode extends SimpleNode {
  public ObjectTypeNode(int id) {
    super(id);
  }

  public ObjectTypeNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7db2df045e083d6bc56bf09a46cab393 (do not edit this line) */
