/* Generated By:JJTree: Do not edit this line. PrimitiveTypeNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class PrimitiveTypeNode extends SimpleNode {
  public PrimitiveTypeNode(int id) {
    super(id);
  }

  public PrimitiveTypeNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa71142cefd79b11db2f0341dfb1cc43 (do not edit this line) */
