/* Generated By:JavaCC: Do not edit this line. XYZParserTreeConstants.java Version 4.2 */
package ast;

public interface XYZParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTPROGRAM = 2;
  public int JJTMAINCLASS = 3;
  public int JJTCLASSDECL = 4;
  public int JJTEXTENDNODE = 5;
  public int JJTSTATEMENTNODE = 6;
  public int JJTIFSTATEMENTNODE = 7;
  public int JJTELSENODE = 8;
  public int JJTWHILESTATEMENTNODE = 9;
  public int JJTDOWHILESTATEMENT = 10;
  public int JJTSINGLESTATEMENTNODE = 11;
  public int JJTPRINTSTATEMENTNODE = 12;
  public int JJTVARDECLNODE = 13;
  public int JJTMETHODNODE = 14;
  public int JJTFORMALLISTNODE = 15;
  public int JJTFORMALRESTNODE = 16;
  public int JJTRETURNSTATEMENTNODE = 17;
  public int JJTPRIMITIVETYPENODE = 18;
  public int JJTOBJECTTYPENODE = 19;
  public int JJTJUDGEEXPNODE = 20;
  public int JJTNOTEXPNODE = 21;
  public int JJTLESSEXPNODE = 22;
  public int JJTASSIGNSTATEMENTNODE = 23;
  public int JJTASSIGNLEFTNODE = 24;
  public int JJTASSIGNRIGHTNODE = 25;
  public int JJTEXPNODE = 26;
  public int JJTADDEXPNODE = 27;
  public int JJTMINUSEXPNODE = 28;
  public int JJTMULTIEXPNODE = 29;
  public int JJTSIGNEXPNODE = 30;
  public int JJTCALLEXPNODE = 31;
  public int JJTCHILDEXPNODE = 32;
  public int JJTARRAYELEMENTNODE = 33;
  public int JJTIDELEMENTNODE = 34;
  public int JJTCONSTANTELEMENTNODE = 35;
  public int JJTNEWEXPNODE = 36;
  public int JJTIDEXPNODE = 37;
  public int JJTINDEXNODE = 38;
  public int JJTDOTLENGTHNODE = 39;
  public int JJTINVOKEFUNCTIONNODE = 40;
  public int JJTIDNODE = 41;
  public int JJTTHISNODE = 42;
  public int JJTEXPLISTNODE = 43;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Program",
    "MainClass",
    "ClassDecl",
    "ExtendNode",
    "StatementNode",
    "IfStatementNode",
    "ElseNode",
    "WhileStatementNode",
    "DoWhileStatement",
    "SingleStatementNode",
    "PrintStatementNode",
    "VarDeclNode",
    "MethodNode",
    "FormalListNode",
    "FormalRestNode",
    "ReturnStatementNode",
    "PrimitiveTypeNode",
    "ObjectTypeNode",
    "JudgeExpNode",
    "NotExpNode",
    "LessExpNode",
    "AssignStatementNode",
    "AssignLeftNode",
    "AssignRightNode",
    "ExpNode",
    "AddExpNode",
    "MinusExpNode",
    "MultiExpNode",
    "SignExpNode",
    "CallExpNode",
    "ChildExpNode",
    "ArrayElementNode",
    "IDElementNode",
    "ConstantElementNode",
    "NewExpNode",
    "IDExpNode",
    "IndexNode",
    "DotLengthNode",
    "InvokeFunctionNode",
    "IDNode",
    "ThisNode",
    "ExpListNode",
  };
}
/* JavaCC - OriginalChecksum=7da5e83ae740a7d4c564c2ee47c2227b (do not edit this line) */
