/* Generated By:JavaCC: Do not edit this line. XYZParserVisitor.java Version 4.2 */
package ast;

public interface XYZParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Root node, Object data);
  public Object visit(Program node, Object data);
  public Object visit(MainClass node, Object data);
  public Object visit(ClassDecl node, Object data);
  public Object visit(ExtendNode node, Object data);
  public Object visit(StatementNode node, Object data);
  public Object visit(IfStatementNode node, Object data);
  public Object visit(ElseNode node, Object data);
  public Object visit(WhileStatementNode node, Object data);
  public Object visit(DoWhileStatement node, Object data);
  public Object visit(SingleStatementNode node, Object data);
  public Object visit(PrintStatementNode node, Object data);
  public Object visit(VarDeclNode node, Object data);
  public Object visit(MethodNode node, Object data);
  public Object visit(FormalListNode node, Object data);
  public Object visit(FormalRestNode node, Object data);
  public Object visit(ReturnStatementNode node, Object data);
  public Object visit(PrimitiveTypeNode node, Object data);
  public Object visit(ObjectTypeNode node, Object data);
  public Object visit(JudgeExpNode node, Object data);
  public Object visit(NotExpNode node, Object data);
  public Object visit(LessExpNode node, Object data);
  public Object visit(AssignStatementNode node, Object data);
  public Object visit(AssignLeftNode node, Object data);
  public Object visit(AssignRightNode node, Object data);
  public Object visit(ExpNode node, Object data);
  public Object visit(AddExpNode node, Object data);
  public Object visit(MinusExpNode node, Object data);
  public Object visit(MultiExpNode node, Object data);
  public Object visit(SignExpNode node, Object data);
  public Object visit(CallExpNode node, Object data);
  public Object visit(ChildExpNode node, Object data);
  public Object visit(ArrayElementNode node, Object data);
  public Object visit(IDElementNode node, Object data);
  public Object visit(ConstantElementNode node, Object data);
  public Object visit(NewExpNode node, Object data);
  public Object visit(IDExpNode node, Object data);
  public Object visit(IndexNode node, Object data);
  public Object visit(DotLengthNode node, Object data);
  public Object visit(InvokeFunctionNode node, Object data);
  public Object visit(IDNode node, Object data);
  public Object visit(ThisNode node, Object data);
  public Object visit(ExpListNode node, Object data);
}
/* JavaCC - OriginalChecksum=2dd619ce812cafe1dfe0115ddc9c4d16 (do not edit this line) */
