/* Generated By:JavaCC: Do not edit this line. XYZParserTreeConstants.java Version 4.2 */
public interface XYZParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTPROGRAM = 2;
  public int JJTMAINCLASS = 3;
  public int JJTCLASSDECL = 4;
  public int JJTIFSTATEMENTNODE = 5;
  public int JJTWHILESTATEMENTNODE = 6;
  public int JJTSINGLESTATEMENTNODE = 7;
  public int JJTMETHODNODE = 8;
  public int JJTRETURNSTATEMENTNODE = 9;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Program",
    "MainClass",
    "ClassDecl",
    "IfStatementNode",
    "WhileStatementNode",
    "SingleStatementNode",
    "MethodNode",
    "ReturnStatementNode",
  };
}
/* JavaCC - OriginalChecksum=13941f696b6b1a454cff4cc2dc54ab07 (do not edit this line) */
