/* Generated By:JavaCC: Do not edit this line. XYZParserVisitor.java Version 4.2 */
public interface XYZParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Root node, Object data);
  public Object visit(Program node, Object data);
  public Object visit(MainClass node, Object data);
  public Object visit(ClassDecl node, Object data);
  public Object visit(IfStatementNode node, Object data);
  public Object visit(WhileStatementNode node, Object data);
  public Object visit(SingleStatementNode node, Object data);
  public Object visit(MethodNode node, Object data);
  public Object visit(ReturnStatementNode node, Object data);
}
/* JavaCC - OriginalChecksum=9a1fbe7a6b59f46464927e3ea89901c3 (do not edit this line) */
