/* Generated By:JJTree: Do not edit this line. VarDeclNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class VarDeclNode extends SimpleNode {
  public VarDeclNode(int id) {
    super(id);
  }

  public VarDeclNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=426891bc4c9f30ea3a7f7bdd3684d468 (do not edit this line) */
