/* Generated By:JJTree: Do not edit this line. AssignRightNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class AssignRightNode extends SimpleNode {
  public AssignRightNode(int id) {
    super(id);
  }

  public AssignRightNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dd9606b0dd3cde5dc89d0972e7bd23d1 (do not edit this line) */
