/* Generated By:JJTree: Do not edit this line. InvokeFunctionNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class InvokeFunctionNode extends SimpleNode {
  public InvokeFunctionNode(int id) {
    super(id);
  }

  public InvokeFunctionNode(XYZParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XYZParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ff072b0be702c9388f585e211f51aede (do not edit this line) */
